### PR TITLE
Create action to run pytest main branch

### LINKED ISSUE #15: Add github actions workflow to run pytest

### PR DESCRIPTION
**Pull request by Areadrill**
Closes #15 

I believe this does what you want it to. Let me know if not.

### CODE REVIEW

**Comment by pberkes** [comment]
Thank you for the contribution! It would be great to test on Python 3.8 and 3.9. Would you mind adding that please?

**Comment by pberkes** [comment]
Also please run `pytest` verbose mode as `pytest -v`. Thanks!

**Comment by Areadrill** [comment]
I'm actually not sure how to go about that on the same action. Should that be 2 separate actions? Pytest on python 3.8 and pytest on python 3.9?

**Comment by Areadrill** [comment]
ah, nvm. I think I got it.

**Comment by pberkes** [comment]
Thank you! LGTM

**Pull request merged**
